name: test

on: [push, pull_request]

env:
  SCARB_VERSION: 0.5.1

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Install scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v $SCARB_VERSION
      - name: Step 3 - Trying to build
        run: scarb build

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Install scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v $SCARB_VERSION
      - name: Step 3 - Run tests
        run: scarb test

  check-format:
    name: check-format
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Install scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v $SCARB_VERSION
      - name: Step 3 - Check format
        run: scarb fmt --check
      